try:
    print(x)
except:
    print("An error occurred")
finally:
    print("Success")